### ISSUE TITLE
Disk Space not shown when null in console summary after script execution

### ISSUE THREAD

**Issue by Tuttu** [codaamok/Get-CMUnusedSources#4] opened 2019-07-12 09:55 UTC
After the end of the script, if the total size of unused folder is null (Or equal to zero maybe?), it is blank in the summary displayed in the PowerShell console.

```Content objects: 447
Folders at \\XXX\XXX\Installs\Versions Windows 7\0-Applications du master: 767
Folders where access denied: 0
Folders unused: 483
Disk space in "\\XXX\XXX\Installs\Versions Windows 7\0-Applications du master" not used by ConfigMgr conten
t objects (Package, Application):  MB
Runtime: 00:28:53.5391380```

**Comment by ChrisKibble** [comment] 2019-07-12 16:55
If there are 483 unused folders, I'm guessing that something isn't calculating right and not that it's 0 MB (unless you have 483 empty folders).  Just leaving my thoughts here, @codaamok.

**Comment by codaamok** [comment] 2019-07-19 10:09
Yeah this is weird. Even if it were 483 empty folders I can still get 0. Below is an example what that area of the scripts does in brief.

```powershell
PS C:\Users\Adam> Get-ChildItem "C:\Users\Adam\Documents\New Folder" -Directory -Recurse | Select-Object -ExpandProperty FullName | Measure-ChildItem -Unit MB -Digits 2 | Measure-Object Size -Sum | Select-Object -ExpandProperty Sum
0
```

Maybe you could give what's currently in develop a go and see if the issue is still present there?

https://github.com/codaamok/Get-CMUnusedSources/tree/develop

**Comment by Tuttu** [comment] 2019-07-22 08:36
I still get the error with the Dev version. Here's a part the console log after the script has completed its task.
```Content objects: 2531
Folders at \\server\sources$\Installs\Versions Windows 10\9-Correctif: 155
Folders where access denied: 0
Folders unused: 0
Disk space in "\\server\sources$\Installs\Versions Windows 10\9-Correctif" not used by ConfigMgr content objects (P
ackage, Application, Driver, DriverPackage, OperatingSystemImage, OperatingSystemInstaller, BootImage, SoftwareUpdateDep
loymentPackage):  MB
```

**Comment by codaamok** [comment] 2019-07-22 19:54
Okey, I've committed a couple of fixes to address this in `develop` branch. May you give it a shot please? :-)

https://github.com/codaamok/Get-CMUnusedSources/tree/develop

**Comment by Tuttu** [comment] 2019-07-23 07:59
It looks like it's all good with the latest dev version. :)

```
Folders at \\server\sources$\Installs\Versions Windows 10\9-Correctif: 155
Folders where access denied: 0
Folders unused: 0
Disk space in "\\server\sources$\Installs\Versions Windows 10\9-Correctif" not used by ConfigMgr content objects (P
ackage, Application, Driver, DriverPackage, OperatingSystemImage, OperatingSystemInstaller, BootImage, SoftwareUpdateDep
loymentPackage): 0 MB
Runtime: 00:43:32.9802677
```

**Closed as completed** 2019-07-23 10:19 UTC
